### ISSUE TITLE
Update Header

### ISSUE THREAD

**Issue by zarela** [swfl-coders/tech-alliance-website#19]
https://tech-alliance-website.vercel.app/
- [x] Add Logo to Header 
- [x] Remove the text since this is coming from the logo now. Crop logo as needed
![TechAllianceLogo2](https://github.com/swfl-coders/tech-alliance-website/assets/15879194/667a86d5-5496-4d41-8c8e-e5222b1a9b5c)

**Comment by ZaidMarrie** [comment]
Hi, may I work on this issue?

**Comment by zarela** [comment]
Hi @ZaidMarrie, yes, thank you very much.
Please see the message I left on your PR. It's almost there.
