### ISSUE TITLE
Migrate to latest version of Next.js

### ISSUE THREAD

**Issue by zarela** [swfl-coders/tech-alliance-website#23]
We are on a very old version of Next.js which is also causing issues with Vercel builds.

- [x] Update Next,js version
- [x] Update node version on Vercel

Error:

```Error: Node.js Version "14.x" is discontinued and must be upgraded. Please set Node.js Version to 18.x in your Project Settings to use Node.js 18.```

Must use at least version 18

**Comment by ZaidMarrie** [comment]
Is this issue still available to work on?
