### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by zarela** [swfl-coders/tech-alliance-website#31]
Make sure the following are responsive:

- Cards should extend more to take 90 to 95% of the width of the page
- Padding after each card because right now they are too close to each other

**Comment by jonathans199** [comment]
@zarela  this ticket should be closed these cards are responsive already
![Screenshot 2024-12-03 at 6 37 49 PM](https://github.com/user-attachments/assets/e88d805b-9b22-4707-b83e-440195df5079)

**Comment by zarela** [comment]
@jonathans199 thank you! You are right. 
Closing this now. 😄
