### ISSUE TITLE
Add missing socials

### ISSUE THREAD

**Issue by zarela** [swfl-coders/tech-alliance-website#32]
Add missing socials in the footer section:

- LinkedIn: https://www.linkedin.com/company/81290280/
- X/Twitter: https://twitter.com/tech_swfl
- YouTube: https://www.youtube.com/@techallianceswfl
- Discord: https://discord.gg/G5UR26qAbT

**Comment by daynamariejpembie** [comment]
Hi, can I be assigned this issue please?
