### ISSUE TITLE
Add navigation bar

### ISSUE THREAD

**Issue by zarela** [swfl-coders/tech-alliance-website#33]
Mockup: https://sites.google.com/d/1jy-QF80nLAlJPrbHIS9ghZ0sFE3iZV7c/p/1idsBfkzwgaSYPnMiZ3hDI2G1P0OfeqWB/edit

Current header: 
<img width="1233" alt="Screenshot 2024-09-11 at 12 11 29 AM" src="https://github.com/user-attachments/assets/85073967-a90c-474f-9a40-32c9072c0695">

Please feel free to do it as however looks best for you. We are open to suggestions. 

Lets put a menu bar on top of everything. For now we can just add the following tabs:
- Organizations: We will eventually have pages to each group, but for now, we can just do external open tab to their own meetup 
![Screenshot 2024-09-11 at 12 14 49 AM](https://github.com/user-attachments/assets/6a0d5e80-1d47-4b85-b5b1-e75594883ddd)
pages.

- Speakers
![Screenshot 2024-09-11 at 12 14 54 AM](https://github.com/user-attachments/assets/ed46a3b0-729d-4f88-8c80-570cf82ea78e)

- Partners
![Screenshot 2024-09-11 at 12 15 00 AM](https://github.com/user-attachments/assets/848aa124-4b2f-4c81-a3d9-446b74dc828f)

**Comment by jonathans199** [comment]
This will be a start, but need the links
https://github.com/swfl-coders/tech-alliance-website/pull/59
