### ISSUE TITLE
Make footer sticky to the end of the page

### ISSUE THREAD

**Issue by zarela** [swfl-coders/tech-alliance-website#38]
We want to make sure when we start navigating pages if they don't have much content that the footer is at the bottom

<img width="1544" alt="Screenshot 2024-03-10 at 5 59 17 PM" src="https://github.com/swfl-coders/tech-alliance-website/assets/15879194/139a4a12-3b04-458c-a3d6-7fb25b036de8">

This is not an issue on the current home page because we have a lot of content, however, it is an issue when we start having other pages. You can see this at: 

https://www.techallianceswfl.org/events or http://localhost:3000/events

**Comment by elchamojavier** [comment]
test - can you assign this one?

**Comment by daynamariejpembie** [comment]
Is this still being worked on or can I take this one on?

**Comment by zarela** [comment]
I think it was a test only. @daynamariejpembie assigned to you
