### ISSUE TITLE
Phase 1: Add Discord invite link and Discord logo to main page of TA website - ETA: 1/9/25

### ISSUE THREAD

**Issue by ethanlanders** [swfl-coders/tech-alliance-website#46]
The Tech Alliance Discord server is the community's main communication hub. It would be great if we could embed the Discord link prominently on the website so that community members can access the platform.

- [ ] Add the Discord logo next to the Meetup logo
- [ ] Add URL to the logo: https://discord.gg/G5UR26qAbT
- [ ] Modify the Meetup logo to be a button with a call to action

So basically you will have to create two buttons, one next to each other or on top of each other, whatever looks best, but should be like the orange button from the examples (below comments), but in blue

- [ ] Blue button with Discord logo and with link to Discord: Saying: "Join our server"
- [ ] Blue button with Meetup logo and link that says: "Join us on Meetup"

![Screenshot 2024-09-10 at 6 24 48 PM](https://github.com/user-attachments/assets/f42b8e21-a70b-4fc2-9ead-6fce8e8df094)

**Comment by CrystalWernicke** [comment]
We might want to consider doing the same for the other social medias (LinkedIn, Facebook, Twitter, YouTube).

- [ ] https://www.linkedin.com/company/tech-alliance-of-swfl/
- [ ] https://www.facebook.com/techallianceswfl
- [ ] https://x.com/tech_swfl
- [ ] https://www.youtube.com/@techallianceswfl/

_Unrelated to the site:_ We will have to ensure to implement a bot to the TA channel that can filter out spam requests to join the server if we will be imbedding a referral link.

**Comment by ethanlanders** [comment]
We should replace that Meetup button with something like this, see below:
<img width="280" alt="Screenshot 2024-09-17 at 5 10 21 PM" src="https://github.com/user-attachments/assets/7f34e4d5-041c-4115-8b22-c5a737c89915">
<img width="280" alt="Screenshot 2024-09-17 at 5 10 21 PM" src="https://github.com/user-attachments/assets/7f34e4d5-041c-4115-8b22-c5a737c89915">
<img width="344" alt="Screenshot 2024-09-17 at 5 07 22 PM" src="https://github.com/user-attachments/assets/95961ecb-c1d7-4fa6-8a25-1f895f9427e0">
<img width="344" alt="Screenshot 2024-09-17 at 5 07 22 PM" src="https://github.com/user-attachments/assets/95961ecb-c1d7-4fa6-8a25-1f895f9427e0">

**Comment by daynamariejpembie** [comment]
@ethanlanders Would any of these be acceptable? or would it be better to crop the join 1800 members one and use that along with discord image? 

![Meetup-logo](https://github.com/user-attachments/assets/1d906ae9-87ab-4883-bb75-5383ca41055c)
![Meetup-Logo-2016-present](https://github.com/user-attachments/assets/0b244384-2524-4b0e-835d-687a5f6eed8e)

**Comment by allantito** [comment]
@zarela @ethanlanders Please see above.
If needed, I can reassign items along the way to help with PM'ing. I believe I need permissions to do so. 
Tx

**Comment by zarela** [comment]
@daynamariejpembie let's use the same library we are using for the socials. The same you used to add the footer logos.

So basically you will have to create two buttons, one next to each other or on top of each other, whatever looks best, but should be like the orange button above, just blue color that matches

- [ ] Blue button with Discord logo and with link to Discord: Saying: "Join our server"
- [ ] Blue button with Meetup logo and link that says: "Join us on Meetup"

That way both buttons will match 🙂 

@allantito that will be great. I will check into the permissions.
