### ISSUE TITLE
Add each Tech Alliance member group logo to the website

### ISSUE THREAD

**Issue by ethanlanders** [swfl-coders/tech-alliance-website#47]
Our [prototype website](https://sites.google.com/d/1jy-QF80nLAlJPrbHIS9ghZ0sFE3iZV7c/p/1idsBfkzwgaSYPnMiZ3hDI2G1P0OfeqWB/edit?pli=1) has our member groups displayed prominently. We need that for the current website.

Add the below member group logo picture on top of the listed member groups that are currently listed on the Tech Alliance website:
<img width="1019" alt="Screenshot 2024-09-10 at 8 24 34 PM" src="https://github.com/user-attachments/assets/4af2f664-3b9c-4773-865a-320ec2d7fd1b">

Question for developers:
1) Do you think we should use the actual logos, so each group will be one picture? So then when is mobile version each group will have to be stacked on top of each other? or
2) Use this picture that has all groups in one image and when is mobile the picture size adjusts to the width of the screen?

This picture should be placed on top of this section:
![Screenshot 2024-09-10 at 6 35 29 PM](https://github.com/user-attachments/assets/d913d811-ec7c-4b8e-b49a-8233c73dc03d)

**Comment by daynamariejpembie** [comment]
Hi, I am doing both, so the picture you presented for bigger screens and then hiding it for the mobile and using the columns for mobile screens.

**Comment by rashad3412** [comment]
Hey I am going to contribute to this. #50

**Comment by zarela** [comment]
@rashad3412, @daynamariejpembie has already asked for this issue so we are assigning it to her.
Also, can you please let me know how did you found us? We have this project closed to members of our community groups. Thank you!

**Comment by rashad3412** [comment]
Hey I am not a member of the community, how do I become a member? I found it through research I am trying to contribute to my first repo and this is my first time so I really need help on how everything works. Sorry for any confusion I may have caused and thank you for your quick response and feedback.
