### ISSUE TITLE
Add relevant social media links to each member group frame with social media logos w/ hyperlinks

### ISSUE THREAD

**Issue by ethanlanders** [swfl-coders/tech-alliance-website#50]
Each of the Tech Alliance member groups has social media other than Meetup. Within the current member group frames, add hyperlinks with logos to their other social media platforms (e.g. LinkedIn, Twitter, Facebook, ...).

Example:
![Screenshot 2024-09-10 at 7 05 24 PM](https://github.com/user-attachments/assets/c9dde3a8-7735-4ed6-b19f-3bd0e476ecfa)

Up to the developer the design on the icons, can be all the same color on circles or squares or the actual social media logos. The attached picture is just an example.

Groups:

- [ ] SWFL Coders:
Meetup: https://www.meetup.com/SWFL-Coders/
Facebook: https://www.facebook.com/SWFLCoders/
Twitter/X: https://twitter.com/SWFLCoders
LinkedIn: https://www.linkedin.com/company/22325133/
Website: https://www.swflcoders.com/
GitHub: https://github.com/swfl-coders

- [ ] PySWFL
Meetup: https://www.meetup.com/pythonswfl/
Twitter/X: https://twitter.com/PythonSWFL
LinkedIn: https://www.linkedin.com/company/pythonswfl/

- [ ] SWFL Tech Nights:
Meetup: https://www.meetup.com/swfltechnights/
Facebook: https://www.facebook.com/swfltechnights
Twitter/X: https://twitter.com/swfltechnights/
LinkedIn: https://www.linkedin.com/company/swfltechnights/

- [ ] VR & AR of Southwest Florida
Meetup: https://www.meetup.com/vrarswfl/
Facebook: https://www.facebook.com/VRARSWFL/
Twitter/X: https://twitter.com/VRARSWFL/
LinkedIn: https://www.linkedin.com/company/vrarswfl/

- [ ] SWFLSec - Southwest Florida Infosec
Meetup: https://www.meetup.com/SWFLSec-Southwest-Florida-Infosec-Meetup/
Facebook: https://www.facebook.com/swflsec
Instagram: https://www.instagram.com/swflsec
Twitter/X: https://twitter.com/SWFLSec
LinkedIn: https://www.linkedin.com/company/swflsec/

- [ ] Music Producers of Southwest florida
Facebook: https://www.facebook.com/musicproducers.swfl
Instagram: https://www.instagram.com/musicproducers_swfl/

- [ ] SWFL Hackerspace
Meetup: https://www.meetup.com/swfl-hackerspace/
Facebook: https://www.facebook.com/groups/swflhackerspace/
Twitter/X: https://twitter.com/swflhackerspace
LinkedIn: https://www.linkedin.com/company/swfl-hackerspace/

**Comment by AlexVCS** [comment]
Hi, I'd like to work on this issue. Can you assign it to me please?
