### ISSUE TITLE
Update cards to be the same size by collapsing text

### ISSUE THREAD

**Issue by zarela** [swfl-coders/tech-alliance-website#51]
Right now all the cards for each group are different sizes due to some having too much text or little text. 

<img width="1266" alt="Screenshot 2024-09-10 at 6 44 28 PM" src="https://github.com/user-attachments/assets/dc124b16-e206-4194-848c-02f94c4c6ffc">

Let's make sure all the cards have the same size (height and width) by having the same amount of characters for each.
For example: Music Producers has a lot of text, each card could have a description of not longer than 4 lines and just do `...` and a way to hide the rest of the text and collapse it once they click on that card. 

Or any other method you recommend 😄

**Comment by AlexVCS** [comment]
Hey there, I'd like to work on this. Can you assign it to me please?

**Comment by zarela** [comment]
Awesome! Thank you @AlexVCS 
Looks amazing! Great job!
I merged this PR. I will close this issue now
