### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by zarela** [swfl-coders/tech-alliance-website#6]
Include a footer with logos and links to 
Meetup: https://www.meetup.com/g/TechAlliance-SWFL
Facebook group: https://www.facebook.com/groups/techswfl

Example: 
<img width="215" alt="Screen Shot 2022-10-15 at 10 29 06 AM" src="https://user-images.githubusercontent.com/15879194/195991895-98395898-fe69-4f0a-a46d-e07b7a06f976.png">

**Comment by Madelene** [comment]
@zarela Happy to tackle this one as well 😸

**Comment by Madelene** [comment]
Just an FYI: `https://www.meetup.com/g/TechAlliance-SWFL` didn't work, but `https://www.meetup.com/TechAllianceSWFL/` seems to do the trick

**Comment by zarela** [comment]
@Madelene one more change, so sorry I haven't updated the issue and I wasn't super specific. 
We also have LinkedIn and Twitter. I can add those later, but is it possible to just use the circle logos so when we add all the others they are consistent?

Let's use t
<img width="215" alt="Screen Shot 2022-10-15 at 10 29 06 AM" src="https://user-images.githubusercontent.com/15879194/195991895-98395898-fe69-4f0a-a46d-e07b7a06f976.png">
hese type of logos:
