### ISSUE TITLE
Phase 1: Connect Repo notitifcation to GH Team Channel - ETA: 1/9/25

### ISSUE THREAD

**Issue by allantito** [swfl-coders/tech-alliance-website#65]

**Comment by allantito** [comment]
cc @zarela

**Comment by zarela** [comment]
@allantito I just need the code from you to add it to the repo: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks

**Comment by allantito** [comment]
https://discord.com/api/webhooks/1313601614921207880/VTKKb131ax-YAW0oGqY7_SFL0sgefnXU00w8FKNdk8PscaREjgxEppZ9OvhtLjbvjDmX

@zarela Could you please try the above URL - Tx

**Comment by zarela** [comment]
@allantito I added the webhook. Not sure if you received the notification, but I was also able to create a channel on our server and receive notifications there (on my server). 
Please confirm you've seen it :)

**Comment by allantito** [comment]
Webhook connected internally by Zarela. Closing item.
