### ISSUE TITLE
Add Vite as testing framework

### ISSUE THREAD

**Issue by davidstevenrose** [swfl-coders/tech-alliance-website#71]
@zarela @CrystalWernicke I'd like to contribute Vite as a testing framework to this project. I have my PR ready. I updated the readme with testing instructions and included a few tests for the header of the website.

**Comment by zarela** [comment]
Hi David! Thank you! 
I was unfamiliar with Vitest, but after researching seems much more simple and easier to maintain than the other popular ones like Jest. 
Thank you! Make sure you have your GitHub account linked to Hacktoberfest. I added the labels so you can get credit for it.

Thank you for updating the `readme` too. It's perfect!
