### ISSUE TITLE
Add shadow under social media icons for each group card

### ISSUE THREAD

**Issue by ethanlanders** [swfl-coders/tech-alliance-website#82]
The websites of each TA group card now have social media icons. If you click on an icon, you will be redirected to the group's social media. 

I think if we add a shadow underneath each social media icon when the cursor hovers over them, it will be more evident to users that the icons do, in fact, lead to another site. Currently, hovering over the group card produces a shadow for it, but clicking the card just leads to the group Meetup page.

<img width="402" alt="Screenshot 2024-10-22 at 12 02 12 PM" src="https://github.com/user-attachments/assets/d54b6460-9abd-425a-998b-1987e6ad52c7">

**Comment by daynamariejpembie** [comment]
I would like to work on this please :)

**Comment by zarela** [comment]
Good job! Looks beautiful. Thank you Dayna!
